// <auto-generated />
using System;
using Clube_Uniao_Desportiva_Atalaiense.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clube_Uniao_Desportiva_Atalaiense.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clube_Uniao_Desportiva_Atalaiense.Models.Equipa", b =>
                {
                    b.Property<int>("EquipaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipaId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipaId");

                    b.ToTable("Equipas");
                });

            modelBuilder.Entity("Clube_Uniao_Desportiva_Atalaiense.Models.Favorito", b =>
                {
                    b.Property<string>("UtilizadorUsername")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<int>("EquipaId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("UtilizadorUsername", "EquipaId");

                    b.HasIndex("EquipaId");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("Clube_Uniao_Desportiva_Atalaiense.Models.Jogador", b =>
                {
                    b.Property<int>("JogadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JogadorId"));

                    b.Property<int>("EquipaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JogadorId");

                    b.HasIndex("EquipaId");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("Clube_Uniao_Desportiva_Atalaiense.Models.JogadorJogo", b =>
                {
                    b.Property<int>("JogadorId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("JogoId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Assistencias")
                        .HasColumnType("int");

                    b.Property<int>("Golos")
                        .HasColumnType("int");

                    b.HasKey("JogadorId", "JogoId");

                    b.HasIndex("JogoId");

                    b.ToTable("JogadoresJogos");
                });

            modelBuilder.Entity("Clube_Uniao_Desportiva_Atalaiense.Models.Jogo", b =>
                {
                    b.Property<int>("JogoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JogoId"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipaId")
                        .HasColumnType("int");

                    b.HasKey("JogoId");

                    b.HasIndex("EquipaId");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("Clube_Uniao_Desportiva_Atalaiense.Models.Loja", b =>
                {
                    b.Property<int>("LojaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LojaId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LojaId");

                    b.ToTable("Loja");
                });

            modelBuilder.Entity("Clube_Uniao_Desportiva_Atalaiense.Models.Utilizador", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("Clube_Uniao_Desportiva_Atalaiense.Models.Favorito", b =>
                {
                    b.HasOne("Clube_Uniao_Desportiva_Atalaiense.Models.Equipa", "Equipa")
                        .WithMany("Favoritos")
                        .HasForeignKey("EquipaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clube_Uniao_Desportiva_Atalaiense.Models.Utilizador", "Utilizador")
                        .WithMany("Favoritos")
                        .HasForeignKey("UtilizadorUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipa");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("Clube_Uniao_Desportiva_Atalaiense.Models.Jogador", b =>
                {
                    b.HasOne("Clube_Uniao_Desportiva_Atalaiense.Models.Equipa", "Equipa")
                        .WithMany("Jogadores")
                        .HasForeignKey("EquipaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipa");
                });

            modelBuilder.Entity("Clube_Uniao_Desportiva_Atalaiense.Models.JogadorJogo", b =>
                {
                    b.HasOne("Clube_Uniao_Desportiva_Atalaiense.Models.Jogador", "Jogador")
                        .WithMany("JogadoresJogos")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clube_Uniao_Desportiva_Atalaiense.Models.Jogo", "Jogo")
                        .WithMany("JogadoresJogos")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("Clube_Uniao_Desportiva_Atalaiense.Models.Jogo", b =>
                {
                    b.HasOne("Clube_Uniao_Desportiva_Atalaiense.Models.Equipa", "Equipa")
                        .WithMany("Jogos")
                        .HasForeignKey("EquipaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipa");
                });

            modelBuilder.Entity("Clube_Uniao_Desportiva_Atalaiense.Models.Equipa", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("Jogadores");

                    b.Navigation("Jogos");
                });

            modelBuilder.Entity("Clube_Uniao_Desportiva_Atalaiense.Models.Jogador", b =>
                {
                    b.Navigation("JogadoresJogos");
                });

            modelBuilder.Entity("Clube_Uniao_Desportiva_Atalaiense.Models.Jogo", b =>
                {
                    b.Navigation("JogadoresJogos");
                });

            modelBuilder.Entity("Clube_Uniao_Desportiva_Atalaiense.Models.Utilizador", b =>
                {
                    b.Navigation("Favoritos");
                });
#pragma warning restore 612, 618
        }
    }
}
